config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("", include("core.urls", namespace="core")),
    path("products/", include("products.urls", namespace="products")),
    path("users/", include("users.urls", namespace="users")),
    path("admin/", admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/urls.py
from django.urls import path
from products import views as product_views

app_name = "core"

urlpatterns = [path("", product_views.HomeView.as_view(), name="home")]

products/urls.py
from django.urls import path
from . import views

app_name = "products"

urlpatterns = [
    path("<int:pk>", views.ProductDetail.as_view(), name="detail"),
    path("search/", views.SearchView.as_view(), name="search"),
]

templates/base.html
<!DOCTYPE html>
<html lang="kr">

<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <meta http-equiv="X-UA-Compatible" content="ie=edge" />
  <title>{% block page_title %}{% endblock page_title %}| GS</title>
</head>

<body>
  <header>
    {% include "partials/nav.html" %}
    {% block search-bar %}
    <form method="get" action="{% url "products:search" %}">
      <input name="제품이름" placeholder="여기에 검색하세요" />
    </form>
    {% endblock search-bar %}
  </header>

  {% block content %}{% endblock %}

  {% include "partials/footer.html" %}
</body>

</html>